pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'devopswithdj', 
                url: 'https://github.com/devopswithdj/jenkins-projects.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    ls
                    echo 'Buid Docker Image'
                    cd jenkins-projects/python-jenkins-argocd-k8s
                    docker build -t devopswithdj/todo-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push devopswithdj/todo-app:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        // stage('Checkout K8S manifest SCM'){
        //     steps {
        //         git credentialsId: 'devopswithdj', 
        //         url: 'https://github.com/devopswithdj/jenkins-projects.git',
        //         branch: 'main'
        //     }
        // }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'devopswithdj', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cd jenkins-projects/python-jenkins-argocd-k8s
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/devopswithdj/jenkins-projects.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
