pipeline {
    agent none

    stages {
        stage('Front end') {
            agent {
                docker { image 'node:alpine3.22' }
            }
            steps {
                sh 'node --version'
            }
        }
        stage('Database') {
            agent {
                docker { image 'mysql:latest' }
            }
            steps {
                sh 'mysql --version'
            }
        }
    }
}